// packages/service/app/src/lib/components/Header.svelte
<script lang="ts">
  import { page } from "$app/state";
  import { goto } from "$app/navigation";
  import { signOut } from "$lib/auth-client";
  import Avatar from "./Avatar.svelte";
  import Button from "./ui/button/button.svelte";

  export type DisplayUser = { email: string; name: string; image?: string };

  let {
    user,
    isUnderConstruction,
  }: {
    user: DisplayUser | null;
    isUnderConstruction: boolean;
  } = $props();

  let isOpen = $state(false);

  const navLinks = [
    { href: "/dashboard", label: "Dashboard" },
    { href: "/sources", label: "Sources" },
    { href: "/clients", label: "Clients" },
  ];

  function isActiveLink(href: string): boolean {
    const path = page.url?.pathname ?? "";
    if (href === "/dashboard") {
      return path === "/dashboard";
    }
    return path.startsWith(href);
  }

  async function handleLogout() {
    await signOut();
    goto("/login");
  }
</script>

<header class="sticky top-0 z-50 w-full bg-white shadow-sm dark:bg-gray-800">
  <div class="container mx-auto px-4">
    <div class="flex h-16 items-center justify-between">
      <div class="flex items-center gap-2">
        <a
          href={user ? "/dashboard" : "/"}
          class="text-xl font-bold text-gray-900 dark:text-white"
          aria-label={user ? "Go to dashboard" : "Go to home"}
        >
          <img
            src="/logo.svg"
            alt="Contfu"
            height={64}
            width={178}
            class="h-12 hidden md:block"
          />
          <img
            src="/favicon.svg"
            alt="Contfu"
            height={64}
            width={64}
            class="h-12 block md:hidden"
          />
        </a>
      </div>
      {#if !isUnderConstruction}
        <nav class="flex h-full items-center sm:gap-1 md:gap-2">
          {#if user}
            {#each navLinks as { href, label }}
              <a
                {href}
                class="hidden rounded-md px-3 py-2 text-sm font-medium transition-colors sm:block {isActiveLink(href)
                  ? 'bg-gray-100 text-gray-900 dark:bg-gray-700 dark:text-white'
                  : 'text-gray-600 hover:bg-gray-100 hover:text-gray-900 dark:text-gray-300 dark:hover:bg-gray-700 dark:hover:text-white'}"
              >
                {label}
              </a>
            {/each}
            <div class="relative flex h-full items-center">
              <button
                class="peer flex h-14 items-center space-x-2 rounded-lg px-4 py-0 text-gray-600 hover:bg-gray-100 dark:text-gray-300 dark:hover:bg-gray-700"
                onclick={(e) => {
                  if (isOpen) e.currentTarget.blur();
                  else isOpen = true;
                }}
                onblur={() => (isOpen = false)}
              >
                <Avatar {user} />
              </button>
              <div
                class="absolute right-0 top-14 mt-2 hidden w-48 bg-white py-2 shadow-lg peer-focus:block dark:bg-gray-800"
                onmousedown={(e) => e.preventDefault()}
              >
                <span
                  class="block w-full px-4 py-2 text-gray-400 dark:text-gray-500"
                >
                  {user.name}
                </span>
                <a
                  href="/billing"
                  class="block w-full px-4 py-2 text-left text-gray-700 hover:bg-gray-100 dark:text-gray-300 dark:hover:bg-gray-700"
                >
                  Billing
                </a>
                <button
                  type="button"
                  onclick={handleLogout}
                  class="block w-full px-4 py-2 text-left text-gray-700 hover:bg-gray-100 dark:text-gray-300 dark:hover:bg-gray-700"
                >
                  Logout
                </button>
              </div>
            </div>
          {:else}
            <Button variant="link" href="/#features">Features</Button>
            <Button variant="link" href="/#pricing">Pricing</Button>
            <Button variant="default" href="/login">Login</Button>
          {/if}
        </nav>
      {/if}
    </div>
  </div>
</header>

// packages/server/ui/src/components/ui/Header.tsx
import { component$, useSignal } from "@builder.io/qwik";
import type { ActionStore } from "@builder.io/qwik-city";
import { Form, Link } from "@builder.io/qwik-city";
import type { DisplayUser } from "~/server/auth/session";
import Avatar from "./Avatar";

export default component$(
  ({
    user,
    logout,
    isUnderConstruction,
  }: {
    user: DisplayUser | null;
    logout: ActionStore<never, Record<string, unknown>, true>;
    isUnderConstruction: boolean;
  }) => {
    const isOpen = useSignal(false);

    return (
      <header class="bg-white shadow-sm dark:bg-gray-800">
        <div class="container mx-auto px-4">
          <div class="flex h-16 items-center justify-between">
            <div class="flex items-center gap-2">
              <Link
                href={user ? "/dashboard" : "/"}
                class="text-xl font-bold text-gray-900 dark:text-white"
              >
                <img
                  src="/logo.svg"
                  alt="Contfu"
                  height={64}
                  width={178}
                  class="h-12"
                />
              </Link>
            </div>
            {!isUnderConstruction && (
              <nav class="flex h-full items-center space-x-4">
                {user ? (
                  <div class="relative flex h-full items-center">
                    <button
                      class="peer flex h-14 items-center space-x-2 rounded-lg px-4 py-0 text-gray-600 hover:bg-gray-100 dark:text-gray-300 dark:hover:bg-gray-700"
                      onClick$={(_, b) => {
                        if (isOpen.value) b.blur();
                        else isOpen.value = true;
                      }}
                      onBlur$={() => {
                        isOpen.value = false;
                      }}
                    >
                      <Avatar user={user} />
                    </button>
                    <div
                      class="absolute right-0 top-14 mt-2 hidden w-48 bg-white py-2 shadow-lg peer-focus:block dark:bg-gray-800"
                      preventdefault:mousedown
                    >
                      <span class="block w-full px-4 py-2 text-gray-400 dark:text-gray-500">
                        {user.name}
                      </span>
                      <Form action={logout}>
                        <button
                          type="submit"
                          class="block w-full px-4 py-2 text-left text-gray-700 hover:bg-gray-100 dark:text-gray-300 dark:hover:bg-gray-700"
                        >
                          Logout
                        </button>
                      </Form>
                    </div>
                  </div>
                ) : (
                  <>
                    <Link
                      href="/#features"
                      class="text-gray-600 hover:text-gray-900 dark:text-gray-300 dark:hover:text-white"
                    >
                      Features
                    </Link>
                    <Link
                      href="/#pricing"
                      class="text-gray-600 hover:text-gray-900 dark:text-gray-300 dark:hover:text-white"
                    >
                      Pricing
                    </Link>
                    <Link
                      href="/login"
                      class="bg-primary-400 hover:bg-primary-500 dark:bg-primary-500 dark:hover:bg-primary-400 rounded-lg px-4 py-2 text-sm font-medium text-white"
                    >
                      Login
                    </Link>
                  </>
                )}
              </nav>
            )}
          </div>
        </div>
      </header>
    );
  },
);
