// packages/server/ui/src/routes/under-construction/index.tsx
import { component$ } from "@builder.io/qwik";
import type { DocumentHead } from "@builder.io/qwik-city";
import LogoSquare from "../../../public/logo-square.svg?jsx";

export default component$(() => {
  return (
    <div class="flex min-h-screen flex-col items-center justify-center bg-gray-50 p-4 dark:bg-gray-900">
      <div class="mx-auto max-w-2xl text-center">
        <LogoSquare class="mx-auto mb-8 h-32 w-32" />
        <h1 class="mb-4 text-4xl font-bold text-gray-900 dark:text-white">
          Coming Soon
        </h1>
        <p class="mb-8 text-xl text-gray-600 dark:text-gray-300">
          We're working hard to bring you something amazing. Our application is
          currently under construction.
        </p>
        <div class="text-sm text-gray-500 dark:text-gray-400">
          Thank you for your patience!
        </div>
      </div>
    </div>
  );
});

export const head: DocumentHead = {
  title: "Coming Soon",
  meta: [
    {
      name: "description",
      content:
        "Our application is currently under construction. Check back soon!",
    },
  ],
};

// packages/service/app/src/routes/under-construction/+page.svelte
<svelte:head>
  <title>Coming Soon</title>
  <meta name="description" content="Under construction. Check back soon." />
</svelte:head>

<div class="flex min-h-screen flex-col items-center justify-center p-4">
  <div class="max-w-md">
    <p class="text-xs text-muted-foreground mb-4">
      <span class="text-primary">$</span> contfu --status
    </p>
    <h1 class="text-2xl font-semibold mb-4">
      <span class="text-primary">></span> coming soon
    </h1>
    <p class="text-sm text-muted-foreground mb-2">
      We're building something. Check back later.
    </p>
    <p class="text-xs text-muted-foreground">
      process: running<span class="cursor-blink"></span>
    </p>
  </div>
</div>
